name = "Firstname Lastname"
role = "My Role"
email = "me@email.com"
about = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum lectus libero, at placerat felis feugiat at.

Sed malesuada ligula pretium pellentesque fermentum. Phasellus gravida ante augue, eu porta nisi tincidunt in.
Proin rhoncus fringilla metus, vel mattis leo porttitor nec. Donec sit amet ante quis dolor interdum convallis at ut arcu.
Aenean in tellus enim. Ut velit nunc, efficitur non fringilla venenatis, posuere non mauris.
Nulla gravida rutrum ultrices.

Aliquam non dapibus justo. Morbi ornare ante ultrices orci laoreet, et sodales mauris lobortis.
Mauris condimentum in est sed ultricies. Sed semper sem tellus.
"""
skills = [
    "Strength", "Agility", "Intelligence", "Charisma",
    "Perception", "Endurance", "Luck", "Wisdom",
    "Unarmed", "Melee Weapons", "Energy Weapons", "Taunt"
]
show_company_icons = true


# Name will be prepended with "fa-" to use FontAwesome icons, refer to
# https://fontawesome.com/search?ic=free-collection for available icons.
[[socials]]
name = "github"
link = "https://github.com/placeholder"

[[socials]]
name = "linkedin"
link = "https://www.linkedin.com/in/placeholder"


[[languages]]
name = "English"
level = "Native"

[[languages]]
name = "Slur"
level = "Proficient"


[[locations]]
name = "Syndey, Australia"

[[locations]]
name = "Ceres, Asteroid Belt"


##############
# Experience #
##############

[[experiences]]
company = "Google"
link = "https://www.google.com/"
badges = ["Remote"]
title = "Sr Search Specialist (SQL)"
logo = "google.png"
start = "Jun 2077"
end = ""
description = """
I used to search in Google a lot, so I guess you could say I am a Sr Search Specialist or something.
Anyway, this is just a placeholder for the experience section anyway, so I might as well put something here.
"""

[[experiences]]
company = "Amazon"
link = "https://www.yugabyte.com/"
badges = ["On-site"]
title = "Sr Software Engineer (C/C±±)"
logo = "amazon.ico"
start = "Aug 2020"
end = "Jun 2077"
description = """
Aliquam non dapibus justo. Morbi ornare ante ultrices orci laoreet, et sodales mauris lobortis.
Mauris condimentum in est sed ultricies. Sed semper sem tellus.

Ut velit nunc, efficitur non fringilla venenatis, posuere non mauris.
Nulla gravida rutrum ultrices.
"""

[[experiences]]
company = "Facebook"
link = ""
badges = []
title = "Test Subject"
logo = ""
start = "44 AD"
end = "Aug 2020"
description = """
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean interdum lectus libero, at placerat felis feugiat at.
Ut velit nunc, efficitur non fringilla venenatis, posuere non mauris.
"""


#############
# Education #
#############

[[educations]]
name = "Matrian University of Information Technologies"
link = ""
badges = []
title = "Computer Science"
logo = ""
start = 2006
end = 2010
description = """
Co-author of the "Introduction to Intergalactic Programming" textbook.
Graduated with honors, specializing in advanced quantum computing and interstellar data transmission.
"""
